export const products = [
  {
    id: 1,
    name: "Kacamata casual hitam",
    category: "Kacamata",
    price: 15,
    image: "/images/product1.jpg",
    isCart: false,
    description: "Kacamata Fashion dengan desain yang modern dan gaya yang stylish.",
  },
  {
    id: 2,
    name: "Hyejin Dress",
    category: "Dress",
    price: 25,
    image: "/images/product2.jpg",
    isCart: false,
    description: "Dress casual dengan potongan lengan panjang dan desain yang trendi.",
  },
  {
    id: 3,
    name: "Sepatu sneakers Piero Rusher Lux",
    category: "Sepatu",
    price: 35,
    image: "/images/product3.jpg",
    isCart: false,
    description: "Sepatu sneakers dengan gaya streetwear yang trendy.",
  },
  {
    id: 4,
    name: "Long Cargo Pants",
    category: "Celana",
    price: 40,
    image: "/images/product4.jpg",
    isCart: false,
    description: "Celana panjang pria dengan  Ciri khas dari celana ini adalah adanya katong berukuran besar pada bagian kanan dan kiri sisinya.",
  },
  {
    id: 5,
    name: "Midi Dress Korea",
    category: "Dress",
    price: 25,
    image: "/images/product5.jpg",
    isCart: false,
    description: "dress yang memiliki panjang rok sampai lutut atau sedikit ke bawah dan memiliki model yang simpel dan feminin.",
  },
  {
    id: 7,
    name: "Kacamata Photocromic",
    category: "Kacamata",
    price: 18,
    image: "/images/product6.jpg",
    isCart: false,
    description: " kacamata photochromic adalah salah satu jenis lensa kacamata yang warnanya bisa bertransisi menjadi lebih gelap ketika terpapar oleh sinar matahari atau sinar UV lainnya.",
  },
  {
    id: 6,
    name: "Sepatu Ventela Konnijiwa",
    category: "Sepatu",
    price: 18,
    image: "/images/product7.jpg",
    isCart: false,
    description: "Sepatu kolaborasi ventela x jeromepolin dengan nama Konnijiwa.Insole terbuat dari Ultralite Foam menjadikan Ventela sangat empuk dan nyaman dipakai dan pada strip bisa menyala pada kegelapan",
  },
  {
    id: 17,
    name: "bola pohon natal",
    category: "ornamen pohon natal",
    price: 40,
    image: "/images/product9.jpg",
    isCart: false,
    description: "Menambahkan suasana natalmu dengan hiasan bola natal.",
  },
   {
    id: 9,
    name: "bintang pohon natal",
    category: "ornamen pohon natal",
    price: 40,
    image: "/images/product10.jpg",
    isCart: false,
    description: "Dekorasi ujung pohon natal bentuk bintang led.",
  },
  {
    id: 10,
    name: "slinger natal",
    category: "ornamen pohon natal",
    price: 15,
    image: "/images/product11.jpg",
    isCart: false,
    description: "Slinger lentur dan mudah dililit atau dibentuk sesuai keinginan.",
  },
  {
    id: 11,
    name: "dress mini wanita natal",
    category: "pakaian",
    price: 90,
    image: "/images/product12.jpg",
    isCart: false,
    description: "Cocok untuk dipakai saat acara natal.",
  },
  {
    id: 15,
    name: "bandana natal rusa",
    category: "aksesoris",
    price: 5,
    image: "/images/product16.jpg",
    isCart: false,
    description: "Desain baru sangat cantik dan lucu.",
  },
  {
    id: 13,
    name: "syal natal lucu",
    category: "aksesoris",
    price: 23,
    image: "/images/product13.jpg",
    isCart: false,
    description: "Spesial edisi natal dengan desain yang lucu.",
  },
  {
    id: 14,
    name: "topi natal santa claus",
    category: "aksesoris",
    price: 20,
    image: "/images/product15.jpg",
    isCart: false,
    description: "Ayo meriahkan dengan topi santa yang ikonik natal ini.",
  },
    {
    id: 16,
    name: "gift box natal",
    category: "makanan",
    price: 35,
    image: "/images/product17.jpg",
    isCart: false,
    description: "Cocok diberikan untuk orang-orang tersayang.",
  },
];
